"""
Report Generator Module
Creates branded PDF reports with insights and visualizations
"""

import pandas as pd
from typing import Dict, List, Any, Optional
from datetime import datetime
from io import BytesIO


class ReportGenerator:
    """
    Generate professional reports from data analysis
    
    Attributes:
        df (pd.DataFrame): Dataset being reported on
        brand_colors (Dict): Brand color scheme
    """
    
    BRAND_COLORS = {
        'blue': '#003399',
        'gold': '#FFD700',
        'white': '#FFFFFF'
    }
    
    def __init__(self, df: pd.DataFrame, title: str = "Data Analysis Report"):
        """
        Initialize report generator
        
        Args:
            df (pd.DataFrame): Dataset to report on
            title (str): Report title
        """
        self.df = df
        self.title = title
        self.sections = []
    
    def add_executive_summary(self, summary: str):
        """Add executive summary section"""
        self.sections.append({
            'type': 'executive_summary',
            'content': summary
        })
    
    def add_insights(self, insights: List[str]):
        """Add key insights section"""
        self.sections.append({
            'type': 'insights',
            'content': insights
        })
    
    def add_statistics(self, stats: pd.DataFrame):
        """Add statistics table"""
        self.sections.append({
            'type': 'statistics',
            'content': stats
        })
    
    def add_recommendation(self, recommendations: List[str]):
        """Add recommendations section"""
        self.sections.append({
            'type': 'recommendations',
            'content': recommendations
        })
    
    def generate_markdown(self) -> str:
        """
        Generate markdown version of report
        
        Returns:
            Markdown string
        """
        md = f"""# {self.title}

**Generated by Power Data AI**  
*By Issaka Seogo | Seogo Global Impact*

**Date:** {datetime.now().strftime('%B %d, %Y')}

---

## Dataset Overview

- **Rows:** {len(self.df):,}
- **Columns:** {len(self.df.columns)}
- **Size:** {self.df.memory_usage(deep=True).sum() / 1024**2:.2f} MB

"""
        
        for section in self.sections:
            if section['type'] == 'executive_summary':
                md += f"\n## Executive Summary\n\n{section['content']}\n\n"
            
            elif section['type'] == 'insights':
                md += "\n## Key Insights\n\n"
                for insight in section['content']:
                    md += f"- {insight}\n"
                md += "\n"
            
            elif section['type'] == 'statistics':
                md += "\n## Statistical Summary\n\n"
                md += section['content'].to_markdown()
                md += "\n\n"
            
            elif section['type'] == 'recommendations':
                md += "\n## Recommended Actions\n\n"
                for i, rec in enumerate(section['content'], 1):
                    md += f"{i}. {rec}\n"
                md += "\n"
        
        md += f"""
---

**Power Data AI** – Turning your data into direction.

*For questions or support, contact: issaka.seogo@seogoglobalimpacts.com*
"""
        
        return md
    
    def generate_html(self) -> str:
        """
        Generate HTML version of report with branding
        
        Returns:
            HTML string
        """
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.title}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }}
        
        .header {{
            background: linear-gradient(135deg, {self.BRAND_COLORS['blue']} 0%, #0055CC 100%);
            color: white;
            padding: 40px;
            border-radius: 10px;
            margin-bottom: 30px;
            text-align: center;
        }}
        
        .header h1 {{
            margin: 0;
            color: {self.BRAND_COLORS['gold']};
            font-size: 2.5em;
            text-shadow: 2px 2px 4px rgba(0,0,0,0.3);
        }}
        
        .header p {{
            margin: 10px 0 0 0;
            font-style: italic;
        }}
        
        .content {{
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}
        
        .section {{
            margin-bottom: 30px;
        }}
        
        h2 {{
            color: {self.BRAND_COLORS['blue']};
            border-left: 5px solid {self.BRAND_COLORS['gold']};
            padding-left: 15px;
            margin-top: 30px;
        }}
        
        .insight {{
            background-color: #E6F0FF;
            padding: 15px;
            margin: 10px 0;
            border-left: 4px solid {self.BRAND_COLORS['blue']};
            border-radius: 5px;
        }}
        
        .recommendation {{
            background-color: #FFF9E6;
            padding: 15px;
            margin: 10px 0;
            border-left: 4px solid {self.BRAND_COLORS['gold']};
            border-radius: 5px;
        }}
        
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }}
        
        th {{
            background-color: {self.BRAND_COLORS['blue']};
            color: white;
            padding: 12px;
            text-align: left;
        }}
        
        td {{
            padding: 10px;
            border-bottom: 1px solid #ddd;
        }}
        
        tr:hover {{
            background-color: #f5f5f5;
        }}
        
        .footer {{
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid {self.BRAND_COLORS['gold']};
            color: #666;
            font-style: italic;
        }}
        
        .metric {{
            display: inline-block;
            background: {self.BRAND_COLORS['blue']};
            color: white;
            padding: 10px 20px;
            border-radius: 5px;
            margin: 5px;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{self.title}</h1>
        <p>Generated by Power Data AI</p>
        <p>By Issaka Seogo | Seogo Global Impact</p>
        <p>{datetime.now().strftime('%B %d, %Y')}</p>
    </div>
    
    <div class="content">
        <div class="section">
            <h2>📊 Dataset Overview</h2>
            <span class="metric">Rows: {len(self.df):,}</span>
            <span class="metric">Columns: {len(self.df.columns)}</span>
            <span class="metric">Size: {self.df.memory_usage(deep=True).sum() / 1024**2:.2f} MB</span>
        </div>
"""
        
        for section in self.sections:
            if section['type'] == 'executive_summary':
                html += f"""
        <div class="section">
            <h2>📋 Executive Summary</h2>
            <p>{section['content']}</p>
        </div>
"""
            
            elif section['type'] == 'insights':
                html += """
        <div class="section">
            <h2>💡 Key Insights</h2>
"""
                for insight in section['content']:
                    html += f'            <div class="insight">{insight}</div>\n'
                html += "        </div>\n"
            
            elif section['type'] == 'statistics':
                html += """
        <div class="section">
            <h2>📈 Statistical Summary</h2>
            <table>
"""
                html += "                <tr><th>Metric</th>"
                for col in section['content'].columns:
                    html += f"<th>{col}</th>"
                html += "</tr>\n"
                
                for idx in section['content'].index:
                    html += f"                <tr><td><strong>{idx}</strong></td>"
                    for val in section['content'].loc[idx]:
                        html += f"<td>{val:.2f if isinstance(val, float) else val}</td>"
                    html += "</tr>\n"
                
                html += "            </table>\n        </div>\n"
            
            elif section['type'] == 'recommendations':
                html += """
        <div class="section">
            <h2>🎯 Recommended Actions</h2>
"""
                for i, rec in enumerate(section['content'], 1):
                    html += f'            <div class="recommendation"><strong>{i}.</strong> {rec}</div>\n'
                html += "        </div>\n"
        
        html += """
    </div>
    
    <div class="footer">
        <p><strong>Power Data AI</strong> – Turning your data into direction.</p>
        <p>For questions or support, contact: issaka.seogo@seogoglobalimpacts.com</p>
    </div>
</body>
</html>
"""
        
        return html
    
    def save_html(self, filepath: str):
        """Save report as HTML file"""
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(self.generate_html())
    
    def save_markdown(self, filepath: str):
        """Save report as Markdown file"""
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(self.generate_markdown())


if __name__ == "__main__":
    # Example usage
    from sklearn.datasets import load_iris
    import pandas as pd
    
    iris = load_iris()
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
    df['species'] = iris.target_names[iris.target]
    
    report = ReportGenerator(df, "Iris Dataset Analysis")
    
    report.add_executive_summary(
        "This analysis examines the classic Iris dataset, containing measurements "
        "of 150 iris flowers across three species. The data shows clear patterns "
        "that enable species classification based on petal and sepal dimensions."
    )
    
    report.add_insights([
        "Petal length and width show strong discriminative power between species",
        "Setosa species is clearly separable from the other two",
        "No missing values detected in the dataset",
        "Strong positive correlation between petal length and width (0.96)"
    ])
    
    report.add_statistics(df.describe())
    
    report.add_recommendation([
        "Use petal measurements as primary features for species classification",
        "Consider logistic regression or decision trees for modeling",
        "Collect additional samples of Versicolor and Virginica for better separation"
    ])
    
    # Generate outputs
    print("Generating reports...")
    report.save_html("/home/claude/powerdata-ai-enhanced/examples/reports/sample_report.html")
    report.save_markdown("/home/claude/powerdata-ai-enhanced/examples/reports/sample_report.md")
    print("✅ Reports generated successfully!")
